version: '3.1'
services:
  flask:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - "./src:/projects"
    tty: true
    environment:
      TZ: Asia/Tokyo
  api_mongo:
    platform: linux/x86_64
    image: mongo:3.6.5
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /var/lib/mongo_data:/data/db
      - ./configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  api_mongo-express:
    platform: linux/x86_64
    image: mongo-express
    restart: always
    links:
      - 'api_mongo:mongo'
    ports:
      - 10081:8081
    environment:
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - api_mongo
