import os
from pymongo import MongoClient

MONGO_DATABASE_NAME = os.environ.get("MONGO_DATABASE_NAME")
MONGO_DATABASE_USER = os.environ.get("MONGO_DATABASE_USER")
MONGO_DATABASE_PASSWORD = os.environ.get("MONGO_DATABASE_PASSWORD")
MONGO_DATABASE_CONTAINER_NAME = os.environ.get("MONGO_DATABASE_CONTAINER_NAME")
MONGO_DATABASE_PORT = os.environ.get("MONGO_DATABASE_PORT")

DATABASE_URL = "%s://%s:%s@%s:%s" % (
    MONGO_DATABASE_NAME, MONGO_DATABASE_USER, MONGO_DATABASE_PASSWORD, MONGO_DATABASE_CONTAINER_NAME, MONGO_DATABASE_PORT)

print("DATABASE_URL: " + DATABASE_URL)

client = MongoClient(DATABASE_URL)
db = client.first_test
